# Generated by Django 4.1.6 on 2023-02-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_alter_contacts_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacts",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="phone",
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
