# Generated by Django 4.1.7 on 2023-02-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0004_provider_contacts_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="contacts",
            name="avatar",
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to="contacts/contact/avatar/"),
        ),
    ]
