# Generated by Django 4.1.7 on 2023-02-23 15:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0005_contacts_avatar"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Contacts",
            new_name="Contact",
        ),
    ]
